### ISSUE TITLE
add RDFa serializer

### ISSUE THREAD

**Issue by elf-pavlik** [rdf-ext/rdf-ext#10]
I found email where @danbri mentions it back in 2007
http://lists.w3.org/Archives/Public/public-rdf-in-xhtml-tf/2007Aug/0170.html

I would find it super useful where I care mostly about providing JSON-LD but can also automatically serve RDFa for various crawlers

Also some existing python package: https://github.com/alexstolz/rdflib-rdfa-serializer

If this works out we could also try to make one for Microdata...

**Comment by bergos** [comment]
This issue was moved to rdf-ext/discussions#13
