### ISSUE TITLE
Provide docs (specs do not count)

### ISSUE THREAD

**Issue by ktk** [rdf-ext/rdf-ext#21]
Based on @semanticfire comments we need some better documentation for RDF-Ext to lower the entrance barrier for new programmers. Suggestions welcome, he mentions JQuery API doc as one example which does this well.

**Comment by ktk** [comment]
Related to Issue #8

**Comment by nicola** [comment]
@bergos let's add some very simple spec on the readme otherwise it becomes hilarious to tell people this is very usable! (it is but people won't know how to use it!)

**Comment by bergos** [comment]
@nicola, @ktk What do you think, could [this](https://github.com/rdf-ext/rdf-ext-spec/blob/gh-pages/API.md) be used as a starting point? The texts are mainly copies from the RDF-Interfaces spec, but it also contains at least headings for new methods.

**Comment by vhf** [comment]
+1

I wanted to use this project but decided against it because of the lack of documentation. I would particularly need the API documentation of each modules.

Also, https://github.com/rdf-ext/ gives the following 404 link: http://bergos.github.io/rdf-ext-spec/

**Comment by tpluscode** [comment]
Base lib and modules definitely need some documentation, at least minimal. Currently it's blindly discovering the API and inspecting unit tests :disappointed:

**Comment by nicola** [comment]
This is really a must @bergos @rdf-ext/owners, let's try and have a meeting on how we can do this

**Comment by ktk** [comment]
I agree. Meeting sounds like a good plan.

**Comment by bergos** [comment]
I would like to have a process like this:

1. core developers create a basic doc
2. users and developers ask stuff that isn't documented on gitter or github issues
3. core developers answer the questions
4. users, developers and core developers add missing stuff to the doc

How do we get that process running?

- Step 4. is very important. Wiki or repo? I expect using the wiki would be easier for most users than using git + markdown + PR. If we use the code repos we would also need to republish the packages to update docs on npm.

- How should we structure it? Everything in the rdf-ext/rdf-ext project? How do we avoid to much fragmentation? I think if it's spread into to many wiki pages and even projects, people get lost.

- Where do we point to the wiki? What's the entry point for most users?

@nicola@ktk all
What do you think?

**Comment by ktk** [comment]
AFAIK the Github Wiki is basically Markdown & Git so that is fine as well as we should be able to get it out of it.

What about a separate repo just for the documentation where we can add docs for all the parts?

**Comment by bergos** [comment]
I created the [documentation repository](https://github.com/rdf-ext/documentation/wiki) and disabled the wiki features for all other repositories. The initial version contains only copies of the README and API.

**Comment by danbri** [comment]
I just came here to say something similar. It is not clear from https://github.com/rdf-ext/rdf-ext-spec/blob/gh-pages/API.md how to use these tools in common situations e.g. a code snippet showing how to parse from a live DOM in the browser (i.e. potentially augmented via Javascript) versus from static dead chunks of text. @bergos  -- things seem a little quiet lately, do you anticipate revisiting this project in 2017?

**Comment by bergos** [comment]
@danbri In 2016 it was mainly a chicken-and-egg problem: Have you seen the develop-branches? I spent some time working on the next release. But it should be in sync with the RDFJS Task Force spec. Participation in that group slows down and speeds up randomly and I'm to busy to align to it. First I have to finish some other projects, than (in 2-3 weeks) I will continue with the RDF-Ext/RDFJS stuff. Also I think it's time to change the process a little bit. I will push the spec with well intentions, but ignore issues without PRs.

**Comment by ktk** [comment]
@danbri I talked with @bergos about the same topic a few weeks ago. We hope to improve this situation soon and present a development roadmap for 2017. However we do not have direct funds available for rdf-ext right now so we might try to raise some external funds to speed up the process. We probably don't need much but it would allow us to focus on it the next months.

**Comment by ktk** [comment]
I'm closing the issue here, we collect everything related to documentation in the repo mentioned above.
