### ISSUE TITLE
Is this possible in CF?

### ISSUE THREAD

**Issue by l00mi** [rdf-ext/rdf-ext#24]
var fragmentsClient = new ldf.FragmentsClient('http://fragments.dbpedia.org/2014/en');
var ldfquery = 'CONSTRUCT { <'+source+'> ?p ?o. ?o <http://www.w3.org/2000/01/rdf-schema#label> ?l} WHERE {<'+source+'> ?p ?o. OPTIONAL {?o <http://www.w3.org/2000/01/rdf-schema#label> ?l.}} LIMIT 100000';

**Comment by bergos** [comment]
This issue was moved to rdf-ext/clownface#1
