### ISSUE TITLE
Turtle parser: CURIEs in lists are not expanded

### ISSUE THREAD

**Issue by retog** [rdf-ext/rdf-ext#26]
Parsing the following turtle

    @base <http://example.org/> .
    @prefix s: <http://schema.example.org/> .
    <me> s:owns ( <Apple> <Orange>).

will (among others) generate the following triples

    _:b36 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <Apple> .
    _:b37 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <Orange> .

It should instead expand the relative IRIs (i.e.. <http://schema.example.org/Book>, <http://example.org/Apple>) .

**Comment by retog** [comment]
Sorry, my bad CURIEs must not be in angular brackets.

**Comment by ktk** [comment]
I think you mean `http://example.org/Apple` and `http://example.org/Orange` right? I don't see any mention of `Book` and the `schema.example.org` namespace.

If this N3.js doing it wrong or is this in RDF-Ext? If N3.js we should probably file a bug for @RubenVerborgh

**Comment by RubenVerborgh** [comment]
Yes, It's a resolution bug in N3.js, will solve together with https://github.com/RubenVerborgh/N3.js/issues/51.

**Comment by RubenVerborgh** [comment]
That was actually quite a major bug. [Fixed now](https://github.com/RubenVerborgh/N3.js/commit/95aae924a1d9feecda5f91d9ba230f1178f602c9). Not sure how this went unnoticed for years!

**Comment by ktk** [comment]
Great thanks for your work Ruben!

**Comment by RubenVerborgh** [comment]
You're welcome! Waiting for a feedback on https://github.com/RubenVerborgh/N3.js/issues/51 to release a new version 0.4.4 with thix fix.

**Comment by bergos** [comment]
My [example code](https://gist.github.com/bergos/aeb8833f39f0049890d0) generates now the following triples using the git version of N3.js:

    _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://example.org/Apple> .
    _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b2 .
    _:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://example.org/Orange> .
    _:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
    <http://example.org/me> <http://schema.example.org/owns> _:b1 .
