### ISSUE TITLE
Add a rdf.parse(mimeType, data, callback) method

### ISSUE THREAD

**Issue by retog** [rdf-ext/rdf-ext#27]
Or does this exist already?

**Comment by ckristo** [comment]
Hi,

I've looked for that as well -- as far as I could find out, rdf-ext does not support that currently, so I've written a quick util function for my project; you can find it here: https://gist.github.com/ckristo/93630ad51b3937fe4246

Based on that function, I've also created a `fetchAndParse` that fetches a remote RDF document and performs parsing based on a given content type or content negotiation when no content type is given.

**Comment by ckristo** [comment]
I stumbled upon the source of `LdpStore` and saw that it implements (some) of these functionality. Maybe this could be extracted to util functions so that others can use it without the need of using LdpStore...

**Comment by retog** [comment]
Hi @ckristo, thanks for the pointers. Maybe you could make a pull request with your util method?

Cheers,
Reto

**Comment by bergos** [comment]
@ckristo You are right about the LdpStore stuff. The parser and serializer mime type map should be part of the utils and LdpStore should use that one. I added the parser stuff to the utils + added a simple mocha test case in the last version (git+npm).

Todo:
* Implement the serializer mime type map + util function + test case
* Replace LdpStore code with utils code

**Comment by ckristo** [comment]
PR for the first TODO ready, see #32 -- was a quite easy exercise based on your work @bergos :-)

Next up: use the new utils functions within LdpStore, here some remaining questions for that:
* What should happen to options.parsers and options.serializers? Can we remove it? Or is there a good reason for keeping it (and allow to disable certain parsers / serializers)
* LdpStore implements another parser for `application/sparql-update` (`LdpStore.serializeSparqlUpdate`) -- should it be available only in LdpStore, or should we expose it and make available in rdf.utils.serialize

**Comment by ckristo** [comment]
Btw.: What about adding a utils function for fetching data and parsing it based on its content type header (like my fetchAndParse method)?

**Comment by bergos** [comment]
Thanks for the patch.

I just created a SparqlUpdateSerializer. Now we have everything to replace the LdpStore code. We should keep the options.parsers and options.serializers. For example the RDFa parser is not feature complete, but maybe someone wants to use it.

I'm not sure where to place the fetch & parse method. After thinking about the SPARQL stuff, maybe the LdpStore (btw. should be forked/renamed to WebStore) is the right place.

**Comment by bergos** [comment]
Implemented in [rdf-mime-type-util](https://github.com/rdf-ext/rdf-mime-type-util)
