### ISSUE TITLE
SparqlStore and arbitrary SPARQL (SELECT) queries

### ISSUE THREAD

**Issue by ckristo** [rdf-ext/rdf-ext#31]
Hi,

as far as I saw, the current SparqlStore implementation does not allow to execute arbitrary SPARQL queries at the moment. It would be useful though if rdf-ext's SparqlStore implementation supports executing arbitrary SPARQL queries given as query string on the remote SPARQL endpoint. I think that rdf-ext should support at least arbitrary SELECT queries. 

What do you think about this idea? cc @bergos

Kind regards,
Chris

**Comment by bergos** [comment]
There is already a private method for update requests, but the method signature isn't suitable for a public interface. So let's collect parameters/options for such a method:

* query string (parameter)
* HTTP method (option, default: GET)
* addition headers (options, default: {})

Something else? Maybe something that could will be translated into a header field, but looks nicer as an own option?

Method name? `.customQuery`, `.customUpdateQuery`?

**Comment by ckristo** [comment]
Is there a need for differentiating between SPARQL SELECT/ASK/CONSTRUCT and SPARQL Update queries? What about `store.executeQuery(queryString, [queryParams={}], [requestOptions={}])` and `store.executeUpdateQuery(queryString, [queryParams={}], [requestOptions={}])` where `queryString` is the actual query string, `queryParams` are parameters that are replaced in `queryString` (cf. [Parameterized-SPARQL-Strings-Jena](https://jena.apache.org/documentation/query/parameterized-sparql-strings.html)) and `requestOptions` are options passed for the request (method, headers, etc.).

**Comment by bergos** [comment]
Your method names + signature looks good. The update method is required, because the endpoint URL is different (options.endpointUrl vs. options.updateUrl).

**Comment by bergos** [comment]
Added both methods with [this commit](https://github.com/rdf-ext/rdf-store-sparql/commit/2d8941590106dd13cef62c2dad5374b58af64d6e).

**Comment by bergos** [comment]
I moved the code to the [sparql-http-client](https://github.com/zazukoians/sparql-http-client) package, because it's not related to RDF-Ext. The rdf-sparql-store is built on top of this library. If you have already a store, you can access the client with `store.client`.
