### ISSUE TITLE
Resolving url paths

### ISSUE THREAD

**Issue by nicola** [rdf-ext/rdf-ext#33]
I am playing around with rdf-ext, it is very cool and intuitive, congrats!

I have the following graph at url [https://nicola.databox.me/profile/card](https://nicola.databox.me/profile/card)

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<>
    <http://purl.org/dc/terms/title> "Nicola's Profile" ;
    a <http://xmlns.com/foaf/0.1/PersonalProfileDocument> ;
    <http://xmlns.com/foaf/0.1/primaryTopic> <#me> .

<#me>
    a <http://xmlns.com/foaf/0.1/Person> ;
    <http://www.w3.org/ns/auth/cert#key> <#key> ;
    <http://www.w3.org/ns/pim/space#preferencesFile> <../Preferences/prefs> .
```

Now, when I do:

```javascript
graph.match('https://nicola.databox.me/profile/card','http://www.w3.org/ns/pim/space#preferencesFile')
```

It returns:
```
https://nicola.databox.me/profile/../Preferences/prefs 
```

Is it possible to resolve the paths in the library?

E.g.
```
https://nicola.databox.me/Preferences/prefs 
```

**Comment by ktk** [comment]
Hi Nicola,

Thanks for the feedback, credits go mainly to @bergos :)

I don't think path resolving is currently implemented, question is is this defined behavior in RDF? And this question could probably be answered by @retog

**Comment by bergos** [comment]
How did you parse the graph? For example the JSON-LD parser would resolve the relative path in the expand step. But like @ktk mentioned, first we need to know if there is a definition? Maybe @RubenVerborgh has an answer to this question.

**Comment by RubenVerborgh** [comment]
The conclusive answer is in the [RDF 1.1 specification](http://www.w3.org/TR/rdf11-concepts/#section-IRIs):

> Relative IRIs must be [resolved against a base IRI](http://tools.ietf.org/html/rfc3986#section-5.2) to make them absolute.

**Comment by RubenVerborgh** [comment]
And this seems to be an N3.js bug: https://github.com/RubenVerborgh/N3.js/issues/51

**Comment by bergos** [comment]
@nicola btw. have you seen Clownface for graph traversing? Here an example how you would fetch the preferences file:

    var cf = rdf.cf.Store(new rdf.promise.Store(new rdf.LdpStore()));

    cf.node('https://nicola.databox.me/profile/card#me')
      .then(function (cf) {
        console.log(cf.out('http://www.w3.org/ns/pim/space#preferencesFile').literal().shift());
      });

**Comment by nicola** [comment]
Of course I have seen it
(I think that should be decoupled from this library as well!!). I was going to build a similar system and I found it!

**Comment by retog** [comment]
@RubenVerborgh it doesn't exactly not happen, the IRI Ref is not kept relative which would be against the specs (except the LDP spec, but that's another story). The thing is that the IRI is not made absolute the right way (i.e. according to the IRI RFC 3987 and RFC 3986): instead of <https://nicola.databox.me/profile/../Preferences/prefs> it should be <https://nicola.databox.me//Preferences/prefs>.

**Comment by nicola** [comment]
I hope that is the case, or it would be a nightmare for me to do that simple operation

**Comment by RubenVerborgh** [comment]
@retog Yes, that's what I mean: the resolving happens by just sticking both parts together, whereas (only) leading sequences of `../` in the relative URL should be removed.

**Comment by nicola** [comment]
I just got a funny: `https://nicola.databox.me/profile/../Preferences/../`

**Comment by RubenVerborgh** [comment]
@nicola But that's something different. 

> IRI equality: Two IRIs are equal if and only if they are equivalent under Simple String Comparison according to section 5.1 of RFC3987. Further normalization must not be performed when comparing IRIs for equality.

In other words: when resolving, we should correctly adapt all leading sequences of `../`, but not any sequences occurring elsewhere. E.g., resolving `../Preferences/../` against `https://nicola.databox.me/profile/` must result in `https://nicola.databox.me/Preferences/../`.

**Comment by RubenVerborgh** [comment]
Fixed in https://github.com/RubenVerborgh/N3.js/commit/1a0dc71e816273e6251911674338d5e398abf522 without performance impact on other types of IRIs. Will leave people some time to verify the correctness of the solution and then do a 0.4.4 release that includes the fix.

**Comment by RubenVerborgh** [comment]
I actually found the RDF spec to be ambiguous about IRI resolution: https://lists.w3.org/Archives/Public/public-rdf-comments/2015Aug/0000.html. Until an answer is found, I don't feel comfortable to land a release.

**Comment by ktk** [comment]
@RubenVerborgh if I get that correctly the discussion is pretty much set right? Any ETA for new release?

**Comment by RubenVerborgh** [comment]
Not set, no, still actively discussing: https://lists.w3.org/Archives/Public/public-rdf-comments/2015Sep/
ETA: could still be a week.

**Comment by ktk** [comment]
Ah didn't notice that I only saw postings in August in the web interface of the list, thanks for the link.

**Comment by retog** [comment]
@RubenVerborgh iiuc the spec ambiguity only applies when the Turtle document contains non-normalized non-relative IRIs (i.e. the document contains <https://nicola.databox.me/profile/../Preferences/prefs> as base IRI or as a IRI for a resource). I seems however clear that when a relative IRI with trailing [./|../]* and no other ./ or ../ has to be resolved against a normal based IRI this has to result in a normal resource IRI. So in the example in this issue the resource name should be https://nicola.databox.me/Preferences/prefs rather than https://nicola.databox.me/profile/../Preferences/prefs under any plausible interpretation of the spec.

**Comment by RubenVerborgh** [comment]
@retog Yes indeed, there's no unclarity about this specific case; consequently, the fix for this case was already made 2 weeks ago. However, I'm still waiting for a confirmation for other cases, so the next release of N3.js does IRI resolution correct in _all_ cases, not just this one.

**Comment by RubenVerborgh** [comment]
Released [N3.js 0.4.4](https://github.com/RubenVerborgh/N3.js/tree/v0.4.4) with correct implementation of RFC 3986, which includes the cases in this thread.
