### ISSUE TITLE
Change callback signature from (result, err) to (err, result)

### ISSUE THREAD

**Issue by bergos** [rdf-ext/rdf-ext#42]
The (err, result) signature is standard in the JavaScript world. Many libraries could be used without intermediate function. Changing this could case changes in the [RDF-Interfaces library](https://github.com/bergos/rdf-interfaces).

Later also the RDF-Interfaces spec must be adapted.

**Comment by nicola** [comment]
As I mentioned in the gitter chat, this is a must.

**Comment by retog** [comment]
(err, result) is the standard in node.js, for the callbacks in ecmascript I can't see this pattern. And one could ague that graphs are quite similar to the Arrays of ecmascript. Some backends/implementation may never return an error so the code using them would be more concise without the unnecessary additional argument.

**Comment by bergos** [comment]
This is only the case for async callbacks. Loops, filters, etc. will not use the signature including the error. In the new version callbacks and Promises are supported. Every time a Promise is used, the callback also uses the error parameter.
