### ISSUE TITLE
Triple Stream API

### ISSUE THREAD

**Issue by bergos** [rdf-ext/rdf-ext#43]
We should define an parser/serializer API to stream Triples. The N3.js library would support that feature already.

**Comment by nicola** [comment]
[suggestion] I think every single function that the store and the graph offers should have a `Stream` suffix, eg. `store.match`, should also have `store.matchStream`

**Comment by bergos** [comment]
The abstract store can be used as base class to provide default methods for stores that don't support streaming internal.

**Comment by bergos** [comment]
This issue was moved to rdf-ext/discussions#12
