### ISSUE TITLE
where is browserified version?

### ISSUE THREAD

**Issue by danja** [rdf-ext/rdf-ext#47]
I'm guessing just a doc issue.

In the readme -
[[
Browser - Just import RDF-Ext
<script src="/js/rdf-ext.js"></script>
]]

But the version in the root dir has lots of require()s in it, and the version in rdf-ext/bin/ starts with:
#!/usr/bin/env node

Suggestions?

**Comment by bergos** [comment]
Sorry, RDF-Ext is in the transition from one big library to are more [modular architecture](https://github.com/rdf-ext/packages). The browserifyied RDF-Ext distribution has now it's own [repository](https://github.com/rdf-ext/rdf-ext-dist).

**Comment by danja** [comment]
ah, ok. Cheers!
