### ISSUE TITLE
travis build are failing

### ISSUE THREAD

**Issue by retog** [rdf-ext/rdf-ext#50]
so far all but one build failed on travis: https://travis-ci.org/rdf-ext/rdf-ext/builds

**Comment by ktk** [comment]
That's not surprising as there is a major refactoring going on, see for example #46. If you check the errors you see why, will need some more commits to get everything fixed.

**Comment by retog** [comment]
One of the main purposes of having tests and continuous integration is to give confidence and safety during refactoring. If the bar stays green nothing was broken. On the other hand, if one one commits a change or a pull request now one gets an email that the build has failed. Such a build failed notification should alarm the committer, however now this is a false alarm leading to desensitization. If one deliberately wants to commit something that doesn't build yet, one should do so to an appropriately labelled branch.

**Comment by bergos** [comment]
You are right, but CI integration was done during the refactoring, not before. Anyway, the code is close to a release candidate, let's focus and code and documentation!
