### ISSUE TITLE
Set withCredentials to true in utils.defaultRequest

### ISSUE THREAD

**Issue by csarven** [rdf-ext/rdf-ext#52]
I think `utils.defaultRequest` in https://github.com/rdf-ext/rdf-ext/blob/b0776c2e597ecec8598fcc7adef8632b3af9e96a/lib/utils-browser.js should use:

```
xhr.withCredentials = true;
```

If the user already has a session cookie, `utils.defaultRequest` doesn't carry it over to subsequent requests.

**Comment by csarven** [comment]
Setting withCredentials may not be a good idea if the request goes through a proxy, and the endpoint returns `Access-Control-Allow-Origin "*"` instead of `Access-Control-Allow-Origin "<Origin URL from the Request>`. Not sure what would be the practice is here.

**Comment by nicola** [comment]
closed in latest https://github.com/rdf-ext/rdf-ext/commit/8a5c6445374c9996fb5b2fb961f8b42c66fe35d9
