### ISSUE TITLE
createLiteral or createTriple cannot handle non-string values

### ISSUE THREAD

**Issue by ktk** [rdf-ext/rdf-ext#53]
I run into an issue while generating triples with a non-string value as literal.

I use the following code (simplifyed):

``` javascript
var bnode = rdf.createBlankNode();

var pgeolat = rdf.createNamedNode('https://schema.org/latitude');
var pgeolong = rdf.createNamedNode('https://schema.org/longitude');

var ogeolat = rdf.createLiteral(geoaddress.value[0].latitude, null, 'http://www.w3.org/2001/XMLSchema#float');
var ogeolong = rdf.createLiteral(geoaddress.value[0].longitude, null, 'http://www.w3.org/2001/XMLSchema#float');

var tlat = rdf.createTriple(bnode, pgeolat, ogeolat);
var tlong = rdf.createTriple(bnode, pgeolong, ogeolong);
```

This results in incomplete triples:

```
_:b18 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://schema.org/GeoCoordinates> .
_:b18 <https://schema.org/latitude> ""^^<http://www.w3.org/2001/XMLSchema#float> .
_:b18 <https://schema.org/longitude> ""^^<http://www.w3.org/2001/XMLSchema#float> .
```

After analyzing what's going on I come to the following conclusion:
- creating a literal from a string works
- creating a literal from a JavaScript datatype which is not a string does not work (did not do much tests though)

I'm not sure if it is going wrong in `createLiteral` or in `createTriple`, the output of the triple looks like this in JSON:

``` json
{
    "interfaceName": "Literal",
    "nominalValue": 45.91907,
    "language": null,
    "datatype": {
        "interfaceName": "NamedNode",
        "nominalValue": "http://www.w3.org/2001/XMLSchema#float"
    }
}
```

**Comment by bergos** [comment]
fixed with in [this commit](https://github.com/rdf-ext/rdf-graph-array/commit/a72e172ed28bce662966d4c6f874520b78072881).

**Comment by ktk** [comment]
Thanks works now!

**Comment by retog** [comment]
The patch is incomplete/buggy because:
- If one creates two literals with different objects evaluating to the same string equals will return false, clearly literals that look the same and serialize the same are equals
- Equal will return false when comparing with a string but it returns true when the literal was created from a string

Apart from this issues with the patch I think the request is problematic as one might expect that invoking create literals on some particular types (dates, numbers) that appropriate typed literals are created.

**Comment by ktk** [comment]
I'm confused by this comment as I fail to see how this patch has anything to do with comparing objects.

Regarding the second remark, these methods are part of [RDF Interface](https://www.w3.org/TR/rdf-interfaces/#widl-RDFEnvironment-createLiteral-Literal-DOMString-value-DOMString-language-NamedNode-datatype) and no one expects any logic regarding "creating appropriate typed literals", neither did I in this particular context.

The problem was that the serialization didn't contain anything, it was an empty literal instead of a number in case the literal was not a string.

**Comment by bergos** [comment]
@ktk I think @retog is right. [This line](https://github.com/rdf-ext/rdf-graph-array/blob/master/index.js#L55) returns false, if one literal was created from a string and the other one from a number. This should be easy to fix, by adding .toString on both sides.

Automatic datatype detection will be implemented with version 1.0.0. That [topic is on the agenda of the RDFJS Task Force](https://github.com/rdfjs/representation-task-force/issues/17).

**Comment by retog** [comment]
@ktk according to RDF Interfaces `value` is "[t]he value to be represented by the Literal, the value must be a lexical representation of the value", while a String clearly can be a lexical representation I don't think an arbitrary object with a toString method returnig the lexical representation would conform to this requirement.

Also to prevent unexpected changes of the behavior of existing code with the introduction of datatype detection I think it would be safest to support only String for now.

**Comment by ktk** [comment]
From my interpretation this is solved? If not please followup and re-open.
