### ISSUE TITLE
Use request instead

### ISSUE THREAD

**Issue by nicola** [rdf-ext/rdf-ext#57]
Can we just use `request` ?

This current implementation does not follow redirects, for example.
It looks to me we are just reimplementing requests, which shouldn't be much big of a dependency

**Comment by ktk** [comment]
+1 on that

Somewhat related to that: https://github.com/rdf-ext/rdf-ext/issues/57

**Comment by bergos** [comment]
:+1:

I added a request compatible interface to the rdf-ext request in version 0.3.0. The idea is to use the request module in node and maybe browser-request in the browser.

Does browser-request support withCredentials?

**Comment by udp** [comment]
I don't know how it's implemented, but request works in the browser too out of the box.  I use it with browserify.

**Comment by bergos** [comment]
Yes, but I think the output file get's really big. I think without minification it's 1,5MB and that's to much.

**Comment by bergos** [comment]
Version 1.x will use fetch. This will be tracked in the [todo list for version 1.x](https://github.com/rdf-ext/discussions/issues/23).
