### ISSUE TITLE
Use inherits instead of util.inherit

### ISSUE THREAD

**Issue by nicola** [rdf-ext/rdf-ext#61]
Let's use this module: https://www.npmjs.com/package/inherits instead, since it is more browser friendly - in other words, I do not need to import the entire `util` lib just to have this.

**Comment by nicola** [comment]
I just did one, @bergos you can do the others since you might have a better search and replace than mine!

**Comment by nicola** [comment]
@bergos have a good day

**Comment by bergos** [comment]
I merged all PRs. Let's have a look if we can reduce the size of the browserify build some more, before publishing the next release.
