### ISSUE TITLE
Auto-resolve CURIEs on NamedNode creation

### ISSUE THREAD

**Issue by ckristo** [rdf-ext/rdf-ext#62]
Hi,

I noticed that when creating a new named node for a CURIE (e.g. via `rdf.createNamedNode(curieString)`), I must use `rdf.resolve` before to resolve the CURIE to an URI; otherwise it seems to me that RDF-Ext thinks the CURIE is an URI:

`<#me> <foaf:mbox> <mailto:...> .`
  vs.
`<#me> <http://xmlns.com/foaf/0.1/mbox> <mailto:...> .`

Maybe RDF-Ext could check if a CURIE is passed to the rdf.NamedNode constructor and call resolve automatically? According to the RDF Interfaces Spec [1], CURIEs may be passed without further care.

[1] https://www.w3.org/TR/rdf-interfaces/#widl-RDFEnvironment-createNamedNode-NamedNode-DOMString-value

Best regards, Chris

**Comment by ckristo** [comment]
(on interest, I'd be glad to provide a PR)

**Comment by bergos** [comment]
Yes, that would be a nice feature. Why didn't I implement this? A PR is very welcome!

**Comment by ckristo** [comment]
A small problem I do not know how to come around: I need `rdf.PrefixMap` to resolve CURIEs which is defined and set up by the `rdf-ext` module. I currently check if it's set up yet, and if not error out when a CURIE is provided. Another way: make sure to set it up before, but this would require to add `rdf-ext` as dependency to `rdf-graph-array`, which would result in a cyclic dependency I do not like either.

Could you give me a hint how you would solve this?

**Comment by bergos** [comment]
Just do the resolve in the [rdf-ext](https://github.com/rdf-ext/rdf-ext/blob/master/rdf-ext.js#L32) package. That way it would be possible to use the graph implementation without all the prefix stuff.

**Comment by ckristo** [comment]
Then an API user has to take care of using the `create*` factory methods, and not the RDF Interfaces constructor directly. Or what about redefining the constructor function `NamedNode` in `rdf-ext`?

Other possibility I see:
````js
rdf.NamedNode = function (curieOrIri) {
  this.interfaceName = 'NamedNode'
  // - get a pot. CURIE prefix
  var seperator = curieOrIri.indexOf(':')
  var prefix = (seperator !== -1) ? curieOrIri.substr(0, seperator).toLowerCase() : undefined
  // - check for CURIE
  if (prefix !== undefined
      && rdf.prefixes != undefined
      && rdf.prefixes.get(prefix) != undefined) {
    this.nominalValue = rdf.prefixes.resolve(curieOrIri)
  }
  // - IRI
  else {
    this.nominalValue = curieOrIri
  }
}
````
This does only resolve a CURIE when rdf.prefixes -- the PrefixMap -- is defined by another module (usually `rdf-ext`).

BR,

**Comment by bergos** [comment]
But that's intended, that the user should use the .create methods (for this use case). rdf-ext combines a graph implementation with the other utils, like the prefix maps. The classes in the graph packages should just provide a JS representation for the RDF model.

**Comment by ckristo** [comment]
Thanks for the input, wrote a PR accordingly -- see PR #64

**Comment by ktk** [comment]
That should be fixed with the merged PR from what I can see.
