### ISSUE TITLE
Allow to create blank nodes with custom label

### ISSUE THREAD

**Issue by ckristo** [rdf-ext/rdf-ext#63]
Hi,

I currently use SparqlHttp (SparqlStore's client property) to issue a SELECT query. The SPARQL endpoint (DBPedia) returns its results (more or less) according to the SPARQL 1.1 Query Results JSON Format Spec [1] which allows to return a label for a blank node. I've written a small parser implementation for it which may only create a blank node without a label. What about extending the rdf.BlankNode constructor by an optional label? For example:

````js
rdf.BlankNode = function (label) {
    this.interfaceName = 'BlankNode'
    if (label != null) { // checks for null and undefined
        this.nominalValue = label
    } else {
        this.nominalValue = 'b' + (++rdf.BlankNode.nextId)
    }
};
````

[1] https://www.w3.org/TR/sparql11-results-json/

BR, Chris

**Comment by ckristo** [comment]
(on interest, I'd be glad to provide a PR)

**Comment by bergos** [comment]
The next version of RDF-Ext will be 1.x and it will be based on the [spec of the RDFJS Representation Task Force](https://github.com/rdfjs/representation-task-force). And there is already an [issue](https://github.com/rdfjs/representation-task-force/issues/30) for that topic. So maybe it's better to wait a little bit and implement this in the 1.x release.

**Comment by ckristo** [comment]
I'd love to provide a simple parser for SPARQL 1.1 Query Results JSON Format (which allows to process the result of a SPARQL queries with SparqlHttp easily), but it would need a Constructor for a custom blank node label (cf. spec 3.2.2). Due to the fact that the change required to RDF-Ext (rdf-graph-array module) would be marginal and should not have any side effects (when implemented correctly), what about implementing it any way? If the RDFJS Representation Task Force should decide against it, it could be easily reverted.

**Comment by bergos** [comment]
Yes, you are right. Also I think the label parameter will be supported in the spec. Can you please also add a test for it? It must be implemented in the [rdf-test-graph](https://github.com/rdf-ext/rdf-test-graph) package.

**Comment by ckristo** [comment]
Done, but I'd like to check if the test is working fine... 

The test package lacks of documentation, could you give me a quick hint how to execute the tests? Something like `mocha rdf-test-graph/spec.js rdf-graph-array/index.js` I guess? I get a `TypeError: rdf.NamedNode is not a function`, so the rdf-graph-array implementation is not specified correctly...

BR,

**Comment by bergos** [comment]
You can run `mocha node_modules/rdf-test-graph/test/spec.js`. This loads the graph package from the current working directory. So you have to start it from the rdf-graph-array package directory. Or you can use it a command line program. This is also configured in the [package.json](https://github.com/rdf-ext/rdf-graph-array/blob/master/package.json#L8) file of rdf-graph-array. That program needs the path to the package as only parameter.

**Comment by ckristo** [comment]
Done, see https://github.com/rdf-ext/rdf-graph-array/pull/3, https://github.com/rdf-ext/rdf-test-graph/pull/1

**Comment by ckristo** [comment]
PRs were merged, I suppose this can be closed now.
