### ISSUE TITLE
Is it possible to serialize a graph to RDF/XML?

### ISSUE THREAD

**Issue by udp** [rdf-ext/rdf-ext#68]
Am I missing something here or is there currently no XML serializer available?

**Comment by ktk** [comment]
That is correct, there is none right now. Pull requests are for sure welcome but I doubt one of the core-team members will implement that as we don't really see the need for RDF/XML writing.

**Comment by udp** [comment]
OK, thanks.  Was just checking before I started implementing it myself.

**Comment by ktk** [comment]
Ok great, looking forward to the contribution! Closing this one for the moment.

**Comment by udp** [comment]
Very basic attempt: https://github.com/ICO2S/rdf-serializer-xml

So far it seems to work fine for my data but YMMV.
