### ISSUE TITLE
List RDF/XML serializer in documentation

### ISSUE THREAD

**Issue by udp** [rdf-ext/rdf-ext#69]
I've developed a very basic RDF/XML serializer at https://github.com/ICO2S/rdf-serializer-xml.  Please could this be added to the documentation?

More generally, I'm happy to hand this over to the rdf-ext project and continue maintaining it.

**Comment by bergos** [comment]
Thanks for developing the serializer!

I ask already in the gitter channel which requirement a project should fulfill to be handed over to the rdf-ext organization. But we haven't defined the requirements yet. Have you seen the [CONTRIBUTING.md](https://github.com/rdf-ext/rdf-ext/blob/master/CONTRIBUTING.md) files? If you could add some basic tests and format the code in standard code style I think it should be fine to add it to the rdf-ext organization.

**Comment by bergos** [comment]
Your serializer is now listed in the [wiki documentation](https://github.com/rdf-ext/documentation/wiki/Modules).
