### ISSUE TITLE
is there a non-browserify distribution available

### ISSUE THREAD

**Issue by jameslaneconkling** [rdf-ext/rdf-ext#71]
Would be useful to have a standalone distribution of this for the browser that doesn't require a browserify build pipeline.

I love browserify, but in cases where you don't have control over builds (Ember CLI, in my case), a standalone distribution or bower dist is useful.

The `bower.json` file says the main file should be at `dist/rdf-ext.js`, but the dir doesn't exist...

**Comment by jameslaneconkling** [comment]
Well, apparently I don't know what I'm talking about.  The bower install takes care of building the `dist` dir?  That's news to me--thanks bower.

One day, we'll all use npm and everything will be beautiful again.

**Comment by retog** [comment]
In therdf2h project a version made with browserify is deployed:

https://cdn.rawgit.com/rdf2h/rdf2h/v0.3.0/dist/rdf-ext.js

Also I've created several mini-project to create modularized browserified versions such as: 

https://github.com/retog/rdf-store-ldp-browser

I know there is the [distribution-builder](https://github.com/rdf-ext/rdf-ext-dist-builder), but I'm yet looking for an example on how to use it to have travis build releases that are available for download and via CDN (as this is the case with my browserify based external projects).
