### ISSUE TITLE
Support RDFJS DataFactory interface

### ISSUE THREAD

**Issue by dmitrizagidulin** [rdf-ext/rdf-ext#72]
We should probably implement the DataFactory interface for rdf-ext. (Support `namedNode()` instead of, or better yet in addition to, `createNamedNode()`, that sort of thing).

**Comment by dmitrizagidulin** [comment]
I'm happy to make a PR for this, just want to make sure that wouldn't be colliding with anybody.

**Comment by bergos** [comment]
It's already done in the [v1 branch](https://github.com/rdf-ext/rdf-ext/tree/v1). In fact it's implemented in the [rdf-data-model](https://github.com/rdf-ext/rdf-data-model), but rdf-ext inherits from that package. I'm ready to port the other packages to the new interface (PRs to the v1 branches are welcome!), but I'm waiting for more feedback on the [Reader and Writer interfaces](https://github.com/rdfjs/representation-task-force/pull/80).

I don't want to mix the v0.x and v1 stuff. That would just cause more work for testing etc. There are also some other things I want to change in v1.

**Comment by dmitrizagidulin** [comment]
Ah, excellent, ok. I think I was confused by the semantics of `master` vs `v1` -- I assumed master was the latest stuff.
