### ISSUE TITLE
Allow to set Authorization header

### ISSUE THREAD

**Issue by semanticfire** [rdf-ext/rdf-ext#73]
If you have Linked Closed Data behind authorization check its hard to use that right now.
I've hacked headers into the lib once, but a more generic approach would probably be more elegant.

How about supporting JWT ( http://jwt.io ) client side?

This would mean adding a 'Authorization: Bearer <jwt>' to the libs http request handling

**Comment by bergos** [comment]
If you don't need the Store abstraction you can use [rdf-fetch](https://github.com/rdf-ext/rdf-fetch). It's based on the [Fetch](https://fetch.spec.whatwg.org/) standard. I haven't used JWT until now, but I'm sure there is some simple way to use it together with Fetch. Maybe there is even a Fetch wrapper, which you could forward with the [fetch option](https://github.com/rdf-ext/documentation/wiki/rdf-fetch#options).

**Comment by ktk** [comment]
Closing here, needs to be documented somewhere. See linked issue above.
