### ISSUE TITLE
UglifyJS chokes on ES2015 code

### ISSUE THREAD

**Issue by herrstucki** [rdf-ext/rdf-ext#75]
When `require`ing this library in application code which is being bundled (e.g. with [webpack](https://webpack.js.org/)) and minified, UglifyJS will choke on the ES2015 code (`let`, `class`) etc. I assume the same applies when using this library in environments which don't support ES2015+.

To avoid this, the distributed package should be transpiled to ES5, so consumers of this library don't have to worry about transpiling it themselves.

One simple way to do it is to use [Bublé](https://buble.surge.sh/),  run `buble -i src -o lib` in `prepublishOnly` and require modules in `lib` from `index.js`.

The same goes for rdf-fetch et al.

**Comment by l00mi** [comment]
Up to know the library was written rather with the mindset to write in ES2015 and for the nodejs environment and rather _downcompile_ with http://browserify.org/ for Webenvironments.
Isn't this possible with webpack too?

**Comment by herrstucki** [comment]
Yes, but the consensus is to still distribute transpiled ES5 packages to npm. Of course you can transpile third-party packages but it's quite uncommon and an unnecessary overhead on the consumer's side, since there's no way of telling for which packages it's necessary (sometimes not even _how_). I just stumbled over this by accident.

**Comment by bergos** [comment]
The [rdf-ext-dist-builder](https://github.com/rdf-ext/rdf-ext-dist-builder) takes care of that. There is still a [known problem with jsonld.js](https://github.com/rdf-ext/rdf-ext-dist-builder/issues/11). But once it's fixed, that the way to get ES5 rdf-ext packages.

**Comment by bergos** [comment]
The dist builder creates now ES5 distributions.
