### ISSUE TITLE
Using versions 2.0.0 and 2.0.1 in typescript env throws error

### ISSUE THREAD

**Issue by ajaydeshwal** [rdf-ext/rdf-ext#93]
Version 2.0.0 and 2.0.1 throws an error when used in Typescript env. Version 1.3.5. works fine. Following is the error:

Cannot use import statements outside a module

**Comment by bergos** [comment]
Version 2.x uses ESM. `Cannot use import statements outside a module` is a known error message if you use ESM in a CommonJS code base. I'm not a TypeScript expert. I hope these keywords will help you to find a solution within the TypeScript config documentation.
