### ISSUE TITLE
Reduce function?

### ISSUE THREAD

**Issue by lecoqlibre** [rdf-ext/rdf-ext#98]
Hi, the [spec of dataset](https://rdf.js.org/dataset-spec/#dataset-interface) mention the function `reduce (QuadReduceIteratee iteratee, optional any initialValue)`.

Do you plan to add this function to the "rdf-ext" library?

**Comment by bergos** [comment]
Thanks for the hint. Somehow I forgot to add it. I added it with PR #99 and released a new minor version.
